### ISSUE TITLE
Инъекция через конструктор

### ISSUE THREAD

**Issue by Yurka** [Ultingg/ManualConnectionREST#1]
У тебя применяется два разных способа инъекций бинов

1. Через конструктор: 
![image](https://user-images.githubusercontent.com/1749832/91983279-1e42d480-ed34-11ea-8a0c-b44c8ef33b55.png)

2. Через поля:
![image](https://user-images.githubusercontent.com/1749832/91983432-521dfa00-ed34-11ea-8303-b6f13ab5bc64.png)

Нужно выбрать один. Сразу отмечу, что через конструктор будет предпочтительней. 

**К тебе вопрос**, на который надо найти ответ (спрашиваем на интервью): какие есть типы инъекций в сспринге, в чем разница между способами инъекции, какие способы предпочтительнее и (самое важное) почему.

**Comment by Ultingg** [comment]
ответ на вопрос:
есть три основных способа: поле, сеттер, конструктор
худший - это через поле, т.к. это нарушает инкапсуляцию - в поле Private из ниоткуда появляется значение. И невозможно написать модульный тест(это уже пересказ из статьи, тесты я еще не писал)

лучший через конструктор - все как в старом добром java коде только на автомате с помощью Spring

через сеттер - если нет явной необходимости в бизнес логике использовать сеттеры, то лучше использовать конструктор во избежании NullPointerException, например.

https://github.com/Ultingg/ManualConnectionREST/compare/master...MCR-ticket%231
