### ISSUE TITLE
Статик для репозиториев - плохо, инъекция - хорошо

### ISSUE THREAD

**Issue by Yurka** [Ultingg/ManualConnectionREST#11]
![image](https://user-images.githubusercontent.com/1749832/91988742-4e8c7200-ed38-11ea-8890-04449570abbe.png)

Нужно переписать через конструкторную инъекцию, статики используем только там, где не бывает состояния объекта (а у базы состояние есть по умолчанию, мы его как раз меняем))

**Comment by Yurka** [comment]
Место несколько, нужно поправить все.

**Comment by Ultingg** [comment]
DONE
