### ISSUE TITLE
Проблема

### ISSUE THREAD

**Issue by Yurka** [Ultingg/ManualConnectionREST#13]
Вот тут прямо пробелма:
![image](https://user-images.githubusercontent.com/1749832/91989114-c9ee2380-ed38-11ea-8fb9-198ce750d331.png)

Вопрос: что происходит на каждый(!) запрос? 
Каждый раз когда проектируешь API, нужно представлять, что будет если на каждый адрес начнут долбиться 5к запросов в секунду.
Попробуй поправить, обсудим.

**Comment by Ultingg** [comment]
Убрал к херам, он тут не нужно
в бине DataBaseRepository  все процессы происходят
