### ISSUE TITLE
Именование на POST

### ISSUE THREAD

**Issue by Yurka** [Ultingg/ManualConnectionREST#14]
Тут по глаголу (пост) уже понятно, что чтото отправляем, добавлять для этого урл смысла нет:
![image](https://user-images.githubusercontent.com/1749832/91989337-146fa000-ed39-11ea-900a-ff4ec6917d05.png)

Обязательно полистай вот этут подсказку: https://www.restapitutorial.com/
Тут прямо почти всё что нужно и очень коротко с примерами. Реализуй всё как в этой сслыке.

**Comment by Yurka** [comment]
Про остальной нейминг API отмечать не буду, посмотрим как получиться после доработки.

**Comment by Ultingg** [comment]
https://github.com/Ultingg/ManualConnectionREST/pull/40
