### ISSUE TITLE
Тип выражений в запросах

### ISSUE THREAD

**Issue by Yurka** [Ultingg/ManualConnectionREST#16]
![image](https://user-images.githubusercontent.com/1749832/91989753-8d6ef780-ed39-11ea-8a36-1b510ebeb920.png)

Тут важно разобраться, почему Statement плохо и что нужно использовать вместо него (тоже стандартный вопрос на интервью).
Обсудим.

**Comment by Yurka** [comment]
сразу тут отмечу, что 
![image](https://user-images.githubusercontent.com/1749832/91991282-60bbdf80-ed3b-11ea-80ab-3dd92808ef6c.png)
надо переделать, но надо узнать как это делается обычно (более правильно, чем тут).

П.С.
Со строками через "+" лучше не работать, 2 вопроса: 
- почему?
- какие способы применяются? (там есть пара не плохих, надо выбрать из них), это обсудим.

**Comment by Ultingg** [comment]
Как я понял можно использовать  три варианта:
**Statement**  - их лучше использовать как статическую команду, например для создания базы данных с указанием имени бд или таблицы с указанием столбцов, хотят тут можно использовать  ....**PreparedStatement**, т.к. это выражение принимает параметры. Наверное большинство запросов стоит делать через это выражение благодаря это возможности работать с параметрами. (SQL запрос = "Update authors SET first_name = ? WHERE birhtdate = ?" и уже потом я в это выражение вставляю нужные мне значения) 
Select * FROM authors WHERE birhtdate >=?" или можно переписать метод фильтрации по возрасту.

Еще есть **CallableStatement** который может делать IN, INOUT и OUT запросы в БД. Тут тоже можно отличие от PreparedStatement что это выражение используют для создание процедур внутри БД  и в  том что можно получать именно сами значения параметров на выходе. 

Вывод: чаще пользуемся PreparedStatement.
 
Это я в основном чтобы самому разобраться понаписал...

**Comment by Ultingg** [comment]
поправить запросы:
параметризировать
изменить выражение
