### ISSUE TITLE
Инъекция пропертей

### ISSUE THREAD

**Issue by Yurka** [Ultingg/ManualConnectionREST#18]
![image](https://user-images.githubusercontent.com/1749832/91990465-6bc24000-ed3a-11ea-9422-267a637a5490.png)

Тут достаешь проперти через статик, надо переделать на более "спринговый" стиль - через инъекцию пропертей.

Второй шаг: в спринге есть механизм хранения/чтения пропертей, надо им воспользоваться . Более того у тебя уже половина прикручена и надо туда прост оперенести это дело

**Comment by Ultingg** [comment]
https://github.com/Ultingg/ManualConnectionREST/pull/40
