### ISSUE TITLE
Работа со строками по всему проекту

### ISSUE THREAD

**Issue by Yurka** [Ultingg/ManualConnectionREST#21]
(уже отмечал в тикете про запросы) Конкатенация строк это не торт, надо поправить для всего проекта

![image](https://user-images.githubusercontent.com/1749832/91991657-d4f68300-ed3b-11ea-9718-85502aacb776.png)

**Comment by Ultingg** [comment]
![изображение](https://user-images.githubusercontent.com/52838941/92220229-5cf79c80-eea4-11ea-9ff1-5456742ef9bc.png)
 так лучше?)

**Comment by Ultingg** [comment]
MRC-14
https://github.com/Ultingg/ManualConnectionREST/pulls
