### ISSUE TITLE
JPA Data > JDBC Data

### ISSUE THREAD

**Issue by Yurka** [Ultingg/ManualConnectionREST#29]
Ты применил в проекте Spring JPA Data для репо, но это крутоватая тема и требует много приседаний, для простых проектов это оверкилл и есть более подходящая тема: Spring Data JDBC. Перепеши репо на него (т.е. выпилить JPA), будет проще и сильно меньше магии, а значит прозчнее (и в перспективе будет работать быстрее, как это не странно).

**Comment by Yurka** [comment]
Так же все наши запросы что приехали из прошлой версии проекта нужно будет переоформить через spring jdbc data чтобы было в одном стиле, будет в одном стиле.

**Comment by Ultingg** [comment]
https://github.com/Ultingg/ManualConnectionREST/pull/40
