### ISSUE TITLE
url API naming

### ISSUE THREAD

**Issue by Yurka** [Ultingg/ManualConnectionREST#3]
Надо узнать, какие есть варианты именования путей в API, в чем разница, какой сейчас самый популярный и применить его тут. Если разойдемся во мнениях, обсудим )))

![image](https://user-images.githubusercontent.com/1749832/91984318-d5d7e680-ed34-11ea-8ef4-c3fe25b4ad16.png)

**Comment by Yurka** [comment]
Тот что сейчас есть - не самый лучший, поэтому поправим.

**Comment by Ultingg** [comment]
JPA контроллер, Сервис удалил поэтому титкет не актуален
