### ISSUE TITLE
Уже сталкивались, поэтому картинкой

### ISSUE THREAD

**Issue by Yurka** [Ultingg/ManualConnectionREST#4]
![image](https://user-images.githubusercontent.com/1749832/91984832-f738d280-ed34-11ea-85a6-e2b0e8109654.png)

**Comment by Ultingg** [comment]
DONE. 
Я могу закрывать тикеты или мне помечать и ждать проверки?))
(думаю такие повторяющиеся тикеты можно самому закрыть)
