### ISSUE TITLE
Перегруженое выражение

### ISSUE THREAD

**Issue by Yurka** [Ultingg/ManualConnectionREST#5]
В этом месте слишком сложно и плохо читается, попробуй сделать более читабельным, как если бы ты первый раз видел этот код и не был с ним знаком. Обсудим.

![image](https://user-images.githubusercontent.com/1749832/91985653-2f401580-ed35-11ea-93b9-80cc6f168c10.png)

**Comment by Yurka** [comment]
Ну и в других подобных местах, их несколько в коде.
Ключевой момент: читабильность важнее компактности, всегда.

**Comment by Ultingg** [comment]
done.....ну это же понятное сокращение....тогда следуя это логике лямбда выражения не стоит употреблять.... или я что-то не догоняю
вот так надо сделать:
  if (authors != null && !authors.isEmpty())
            return new ResponseEntity<>(authors, OK);
        else {
            return new ResponseEntity<>(NOT_FOUND);
        } ?

**Comment by Yurka** [comment]
Название ветки: MCR-5
В каждый коммит добавляем префикс: "MCT-5: "

**Comment by Ultingg** [comment]
JPA контроллер, Сервис удалил поэтому титкет не актуален
