### ISSUE TITLE
UT checks logic

### ISSUE THREAD

**Issue by Yurka** [Ultingg/ManualConnectionREST#57]
У тебя есть ряд тестов на  authorController.getListOrGetOneByFirstNameAndLastName
в котором в зависимости от параметров вызываются разные методы сервиса authorsSQLService
Надо проверять что был вызван один И НЕ был вызван другой, чтобы точно убедиться что было верно.

![image](https://user-images.githubusercontent.com/1749832/97815310-266cb100-1c9e-11eb-9b99-70a5fdc5a00c.png)

Например тут проверили что нужный метод вызван, но так же надо проверить что ничего другого что есть в этом методе не вызывалось.

**Comment by Yurka** [comment]
Это в ряде тестов есть, не только в этом.

**Comment by Ultingg** [comment]
https://github.com/Ultingg/ManualConnectionREST/pull/70/
