### ISSUE TITLE
Название не совпадает с тестом (или я не понял в чем суть)

### ISSUE THREAD

**Issue by Yurka** [Ultingg/ManualConnectionREST#58]
![image](https://user-images.githubusercontent.com/1749832/97815371-87948480-1c9e-11eb-8a87-d2cc30b579d0.png)

в самом тесте нет нулов

**Comment by Ultingg** [comment]
я тут предположил, что контроллер получает запрос с List json'ов с полями null. поэтому создал список, но не наполнил его объектами.

**Comment by Ultingg** [comment]
https://github.com/Ultingg/ManualConnectionREST/pull/70/
