### ISSUE TITLE
Косяк

### ISSUE THREAD

**Issue by Yurka** [Ultingg/ManualConnectionREST#59]
![image](https://user-images.githubusercontent.com/1749832/97815453-30db7a80-1c9f-11eb-8192-fb7b8b3ad461.png)

Название теста говорит про null хотя внутри речь не о нулл. 
И самое важное: как раз отсутствует тест где бы передавался null, а там похоже конкретно баг ;)
что будет если authorsSQLService.delete(null); ?

**Comment by Ultingg** [comment]
https://github.com/Ultingg/ManualConnectionREST/pull/70/
