### ISSUE TITLE
Форматирование/именование интерфейса

### ISSUE THREAD

**Issue by Yurka** [Ultingg/ManualConnectionREST#6]
![image](https://user-images.githubusercontent.com/1749832/91987050-33206780-ed36-11ea-9dce-67f19f7287ec.png)

Тут всё в кучу, читается как один кусок, хотя на деле это разные методы. 
+есть неисползуемые (убираем всё что не используется)

**Comment by Ultingg** [comment]
Тут я заготовил методы для имплементации, но не додумал как их реализовать)

ср, 2 сент. 2020 г. в 16:06, Yuriy <notifications@github.com>:

**Comment by Ultingg** [comment]
done
