### ISSUE TITLE
Naming теста

### ISSUE THREAD

**Issue by Yurka** [Ultingg/ManualConnectionREST#63]
![image](https://user-images.githubusercontent.com/1749832/97815696-fbd02780-1ca0-11eb-82c9-c2a67ce30061.png)

 структура имени теста:
- что тестируем
- что передаем
- что ожидаем

проблема в п2: ты передаешь конкретное значение, а в названии написано null

проблема в п3: там точно позвращаешься НЕ сакцесс (нот-фаунд)

и получается, что название теста будет: getById_notExistedId_notFound

встречается несколько раз (копипаст бро)))

**Comment by Ultingg** [comment]
https://github.com/Ultingg/ManualConnectionREST/pull/70/
