### ISSUE TITLE
@Builder

### ISSUE THREAD

**Issue by Yurka** [Ultingg/ManualConnectionREST#64]
![image](https://user-images.githubusercontent.com/1749832/97815778-96306b00-1ca1-11eb-9fdd-85afc6eec732.png)

этот замес можно упростить применяя @Builder (от ломбок) над классом. Смело применяй (надо будет везде поправить)

**Comment by Ultingg** [comment]
https://github.com/Ultingg/ManualConnectionREST/pull/70/
