### ISSUE TITLE
Тест с null-вызовом всегда

### ISSUE THREAD

**Issue by Yurka** [Ultingg/ManualConnectionREST#65]
Есть общий лайвхак: как только видишь метод, где есть входной параметр не простого типа (обжект), сразу же добавляй тест на null вызов. Всегда и для всего что попадается.

Пример:
    public Author insert(Author author) 

И так для всего что тестируется (сервис, контроллер...)

**Comment by Ultingg** [comment]
https://github.com/Ultingg/ManualConnectionREST/pull/70/
