### ISSUE TITLE
Почистить код

### ISSUE THREAD

**Issue by Yurka** [Ultingg/ManualConnectionREST#66]
Над всем проектом включая тесты нужно:

1. Прогнать по инспекциям и поправить всё что можно
![image](https://user-images.githubusercontent.com/1749832/97815970-fbd12700-1ca2-11eb-9c60-4bd481733f38.png)

2. Проверить использование пустых строк: много где есть или лишние или отсутствие.

**Comment by Ultingg** [comment]
https://github.com/Ultingg/ManualConnectionREST/pull/70/
