### ISSUE TITLE
Множественные точки выхода

### ISSUE THREAD

**Issue by Yurka** [Ultingg/ManualConnectionREST#7]
![image](https://user-images.githubusercontent.com/1749832/91987234-78449980-ed36-11ea-80f7-8d1cab78c672.png)

Когда много return у метода, это считается не торт, потому что часто можно забыть или не увидеть, где внутри метода этот самый выход есть. Поэтому стараются подобного избегать и делать как можно меньше точек выхода. Только там, где необходимо. Это про читабильность. 
Попробуй переработать тут с учетом вышеотмеченного, обсудим.

**Comment by Ultingg** [comment]
https://github.com/Ultingg/ManualConnectionREST/pull/40
