### ISSUE TITLE
Код возврата для UPDATE

### ISSUE THREAD

**Issue by Yurka** [Ultingg/ManualConnectionREST#9]
![image](https://user-images.githubusercontent.com/1749832/91988453-f48bac80-ed37-11ea-850b-7a78f8caab0f.png)

Тоже можно подобрать коды более "правильные" (Есть специйикация, которая описывает как "по букве", хотя разработка может творить что угодно)))

**Comment by Ultingg** [comment]
stackoverflow рекомендует тот же 204 no_content

**Comment by Ultingg** [comment]
done
